version: '3'
services:
  app1:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - ID=1

  app2:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - ID=2

  app3:
    build: .
    ports:
      - "3002:3000"
    depends_on:
      - db
    environment:
      - ID=3

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
  
  loadbalancer:
    build: ../loadbalancer
    ports:
      - "8080:8080"
    depends_on:
      - app1
      - app2
      - app3

