version: '3'
services:
 
  nameserver:
    build: 
      context: ./nameserver
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nameserver:/usr/src/app 
    links:
      - db
  
  storageserver1:
    build: 
      context: ./storageserver
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./storageserver:/usr/src/app 
    depends_on:
      - nameserver
    links:
      - nameserver
    environment:
      - ID=storageserver1
      - HOST=http://storageserver1:4000
      - CHUNKS_DIR=./chunks1

  storageserver2:
    build: 
      context: ./storageserver
      dockerfile: Dockerfile
    ports:
      - "4001:4000"
    volumes:
      - ./storageserver:/usr/src/app 
    depends_on:
      - nameserver
    links:
      - nameserver
    environment:
      - ID=storageserver2
      - HOST=http://storageserver2:4000
      - CHUNKS_DIR=./chunks2

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
